import type { Metadata } from "next";
import { Berkshire_Swash } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { PhotoProvider } from "@/context/PhotoContext";

const berk_swash = Berkshire_Swash({
  variable: "--font-berk-shwash",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${berk_swash.variable} ${berk_swash.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme='pink' enableSystem disableTransitionOnChange>
          <PhotoProvider>
        <Navbar />
        {children}
        <Footer />
        </PhotoProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
